### ISSUE TITLE
Can you expose the rain sensor in the device driver?

### ISSUE THREAD

**Issue by simondsmason** [csteele-PD/Hubitat-public#1]
I started using this driver a while ago and is great for knowing when the sprinkler is running.  I use lawn check for all automations.  However, I just realized I am still using my old Homeseer installation running in the background to report the state of the rain sensor attached to the etherrain.  So I was wondering if the etherrain driver could be updated to expose the rain sensor to habitat?

**Comment by csteele-PD** [comment]
I don't have a Rain Sensor and got no response when I ordered one. I've added code per the API documentation for the Rain Sensor status.
